### ISSUE TITLE
Content metadata updates on Connect don't propagate to DCF file

### ISSUE THREAD

**Issue by toph-allen** [rstudio/rsconnect#1008]
rsconnect version: 1.0.1

## Description

When content metadata fields (`title`, `name`) are changed on Connect, via the GUI or API, these don't propagate back to the deployment record DCF file. This can cause confusing behavior in the IDE.

## Reproduction

Steps to reproduce:

1. Deploy content to Connect with `rsconnect` or push-button.
2. Change content's `title` on Connect.
3. Deploy an update to the same destination.

Expected behavior:

- The new title from Connect is populated into the DCF file.

Actual behavior:

- The metadata in the DCF file is not updated with new metadata from server.

## Notes

Other metadata is also not updated, e.g. `name` (which can be changed via the API)

The IDE lists available redeploy destinations using the `title` field from the DCF file, so these entries don't reflect changes to the title made in the Connect GUI or via the API. (This is the behavior when the `name`s in Connect and the DCF file match. If they don't match, the deployment workflow shows a text field pre-populated with the IDE project title, even though publishing doesn't update the title on Connect.)

**Comment by toph-allen** [comment]
@hadley This is the issue I mentioned

**Comment by aronatkins** [comment]
`rsconnect::syncAppMetadata()` may help here, but it may need improvements to update a subset of applications. As written, it updates all content owned by local accounts.

**Comment by toph-allen** [comment]
I tested `rsconnect::syncAppMetadata` after changing the title on the server. It updated the deployment record immediately, but I had to restart the server before seeing the change in push-button publishing because of its caching behavior.

**Comment by hadley** [comment]
@aronatkins I don't think `syncAppMetadata()` is as bad as you think it is, because it does only update deployments for the current app directory, which is likely to be a small number. 

@toph-allen are you suggesting that we update the metadata on deploy? Won't this generally be too late, since you'll already have been confused by the dialog? I'm not quite sure I fully understand the problem here.

**Comment by aronatkins** [comment]
@hadley - When I said "subset of applications" I was speaking of its need to gain deployment targeting within a specific project directory. You're absolutely right - it's generally a small number. It does not support, for example, updating the deployment records originally created by a collaborator.

@toph-allen was testing `rsconnect::syncAppMetadata()` as an alternative to having `deployApp()` update the metadata automatically. With confirmation that it works, that is probably sufficient to close this issue.

This issue was originally created because a customer was trying to update these details themselves, resorted to modifying the DCF files, and struggled from there. Folks missed that `syncAppMetadata()` was available.

Closing, as we believe that `syncAppMetadata()` is sufficient.

@toph-allen - Could you confirm that we have an IDE issue tracking that the cached deployment list can grow out-of-date?

**Comment by hadley** [comment]
I think the caching problem might be the same problem as https://github.com/rstudio/rstudio/issues/12707

**Comment by aronatkins** [comment]
Yep. That's it. Thanks, @hadley. I've added a note to that issue indicating that we also see caching problems when updating and removing deployments.

**Comment by toph-allen** [comment]
Updating on deploy would be too late the first time an item redeployed, but not for all subsequent redeploys.

That said, this is the first time we've seen customers ask about this issue, so I think it's fine to close; we can revisit if it comes up again.
