### ISSUE TITLE
cannot deploy packrat-managed Rmd

### ISSUE THREAD

**Issue by aronatkins** [rstudio/rsconnect#104]
Creating this issue here, but it could be an issue with packrat or with the IDE itself.

* Create a new project in the RStudio IDE.
* Create an Rmd and save in that project.
* Enable packrat on that project (Tools -> Project Options -> Packrat)
* Attempt to deploy that Rmd.

```
Preparing to deploy document...DONE
Uploading bundle for document: 14...Error in read.dcf(...) : cannot open the connection
Calls: <Anonymous> ... getPackageDependencies -> readLockFilePackages -> readDcf -> read.dcf
In addition: Warning message:
In read.dcf(...) :
  cannot open compressed file '/private/var/folders/ts/s940qvdj5vj1czr9qh07fvtw0000gn/T/RtmpTrAoxY/file145104a812deb/packrat/packrat.lock', probable reason 'No such file or directory'
Execution halted
```

**Comment by kevinushey** [comment]
The deployment seems to work correctly when done manually in the R console, e.g.

`rsconnect::deployDoc("document.Rmd")`

(in the case where the active project is indeed being managed by `packrat`). It seems like the issue only occurs when attempting to deploy through the IDE. Since the deployment happens in a separate R process, perhaps there is some packrat state that's not getting passed along to the sub-process?

**Comment by kevinushey** [comment]
This should be resolved with https://github.com/rstudio/packrat/commit/3cace80912de0bceaf0854de4895b901813d8009.
