### ISSUE TITLE
shiny package is not bundled if not explicitly specified

### ISSUE THREAD

**Issue by fereshtehRS** [rstudio/rsconnect#121]
rsconnect 0.4.5

- Create an `rmarkdown` document (just the simple template one IDE creates is fine)
- Deploy to `shinyapps.io` using one of these commands:

```
deployApp(appName="app_name", account="account_name", server="shinyapps.io")

deployDoc(doc="filename",appName="app_name", account="acount_name", server="shinyapps.io")
```

- App is deployed but fails to load since `shiny` is not found. 
- Checking manifest file for the app shows that there is no `shiny` package.

Note: If I add `library(shiny)` to the document then `shiny` is bundled. I am pretty sure we didn't need to do this before.

**Comment by jmcphers** [comment]
We only bundle the Shiny package if it's a Shiny R Markdown file (i.e. has `runtime: shiny`). Deploying static R Markdown content to shinyapps.io has never been a supported scenario since shinyapps.io doesn't know how to render static content. It can be made to work (since ordinary R Markdown files can be treated like Shiny R Markdown files in some circumstances) but doesn't work out of the box.

For this reason the IDE doesn't give you the option of publishing static R Markdown files to shinyapps.io (they can only go to Connect or RPubs). 

If we wanted to make this experience better, we should choose among:

a) automatically injecting Shiny when publishing to shinyapps.io (and letting the static file render as a Shiny one after publish);

b) rejecting, with a sensible error, attempts to publish static content to shinyapps.io, or

c) teaching shinyapps.io how to deal with non-Shiny .Rmd files

**Comment by fereshtehRS** [comment]
Ah, right. This wasn't a Shiny R Markdown. My mistake. 
I'll close this and open an enhancement for your suggestions.
