### ISSUE TITLE
Add support for multiple 'lucid' (shinyapps.io) servers

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rsconnect#132]
Originally via request from @jspiewak. Currently, the shinyapps.io server is a singleton -- we always have exactly one. If you want to deploy to a different one (say, a local or staging server), then you set the `rsconnect.shinyapps_url` option to point where you want to go. This however is clumsy and makes it difficult to deploy from the IDE. 

The proposal is roughly to make lucid servers symmetric with Connect servers: that is, it should be possible to have several of them, with a M:M relationship to accounts. Towards that end the following changes should be made:
1. Add a new parameter to `rsconnect::addServer` which indicates whether the server being added is lucid or Connect (in a more user-friendly way, of course!)
2. Store the server type alongside the server URL (in the DCF file in `rsconnect:::serverConfigDir()`)
3. Return the server type in `rsconnect::servers()`. 
4. When creating a client, use the stored server type to create a client of the appropriate type (rather than relying on the server URL to infer the client type)

This will make it possible to have multiple lucid servers, and will make the undocumented option `rsconnect.shinyapps_url` obsolete. 

It will also require a symmetric change on the IDE, which has special behavior attached to the `shinyapps.io` server that will need to be applied to any server of type = lucid, and contains several assumptions that there's only one lucid server (internal bug to be created to track this).

**Comment by hadley** [comment]
@jspiewak @aronatkins do you think that is this still needed? I guess everyone has managed without it for 6 years now 😄

**Comment by aronatkins** [comment]
@ssinnott - Could you describe how you test against your staging/QA instances versus production instances?

**Comment by ssinnott** [comment]
Wow I think this predates me!

We still use `rsconnect.shinyapps_url` for targeting our local development environment and staging environment. So we set this in the session prior to trying to deploy - which changes the url being pointed at by the client [here](https://github.com/rstudio/rsconnect/blob/73278b155d7f66dcf5a918bdef75a4132424f3c5/R/servers.R#L87-L88) to change.

`options(rsconnect.shinyapps_url="https://localhost:7000/v1")`

I think the rational behind this issue is that using this option only works if you deploy using `rsconnect` commands directly. The IDE doesn't pick up this value so you can't use the IDE's push button publishing against our local or staging instances. 

On our end this isn't really a huge issue - more of a nice to have (which is why this was probably never fixed). 

* Locally or on staging we just use `rsconnect` directly (not the IDE).
* If we are testing a new version of the IDE and want to test push button deployment running that against production is also generally fine.
