### ISSUE TITLE
MSstats package

### ISSUE THREAD

**Issue by cristinapasi** [rstudio/rsconnect#179]
Hi I am trying to deploy an app that uses the R package MSstats but I keep getting an error that the package cannot be found.  Can this error be fixed?
Thankyou

**Comment by jspiewak** [comment]
Where are you trying to deploy to, shinyapps.io, an on premise Connect server, somewhere else?
From where did you obtain the MSstats package?

For shinyapps.io, here is the relevant [documentation](http://docs.rstudio.com/shinyapps.io/getting-started.html#using-your-r-packages-in-the-cloud).

**Comment by cristinapasi** [comment]
Hi, I'm deploying on shinyapps.io and MSstats is from Bioconductor https://bioconductor.org/packages/release/bioc/html/MSstats.html.  In the documentation it says that Bioconductor packages are supported, but I keep getting the error.  Should I be doing something in particular?
Thanks

**Comment by kippandrew** [comment]
Bioconductor packages should be supported. Can you send along the exact
error message you are getting?

Thanks
-Andy

**Comment by kevinushey** [comment]
Normally, Bioconductor packages are detected by the presence of a `biocViews` field in the package's DESCRIPTION file, but the `MSstats` package has:

```
bioViews: Bioinformatics, MassSpectrometry, Proteomics, Software
```

Note that this field is set as `bioViews` rather than `biocViews`. This appears to be a 'bug' in the `MSstats` package; note the documentation here: https://www.bioconductor.org/developers/how-to/biocViews/

I suggest reporting this to the package authors / Bioconductor team.

**Comment by cristinapasi** [comment]
That's great, thank you very much.  I will contact them directly.
