### ISSUE TITLE
Unable to retrieve package records for the packages from CRAN

### ISSUE THREAD

**Issue by agricolamz** [rstudio/rsconnect#189]
```
R version 3.4.0 (2017-04-21)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Linux Mint 18.1
packrat_0.4.8-1
rsconnect_0.8
shiny_1.0.3
lingtypology_1.0.5
```
Shiny app works on my local PC, but when I'm try to deploy app, I have an error:
```
Unable to retrieve package records for the following packages:
- 'lingtypology'
```
`lingtypology` is a package created by myself, but it is on [CRAN](https://CRAN.R-project.org/package=lingtypology), so I suppose that it should come from a public CRAN mirror, as written [here](https://support.rstudio.com/hc/en-us/articles/226871467-Package-management-in-RStudio-Connect).

Is it something wrong with `lingtypology`?

**Comment by kippandrew** [comment]
The problem is that `rsconnect` isn't able to detect the package's origin, if the package has been installed locally from source.

As a work around, if the package is on CRAN you should install it using `install.packages()` or `devtools::install_github()` if its on GitHub. This will allow `rsconnect` to detect the package's origin. As the package author, I understand this is a bit annoying.

**Comment by agricolamz** [comment]
@kippandrew, thank you! It helps! I renamed issue, so other can find it.
