### ISSUE TITLE
deployApp should inject shiny dependency

### ISSUE THREAD

**Issue by aronatkins** [rstudio/rsconnect#21]
server.R
```
shinyServer(function(input, output) {})
```
ui.R
```
shinyUI(fluidPage(
  titlePanel("Hello Shiny!")
))
```

I can run the application in the IDE. I can deploy the application both with the IDE and manually via `rsconnect::deployApp`. In both bundles, we do not identify `shiny` as a dependency because it does not explicitly appear in a `library` statement.

The app will fail to start if the deployment target does not have shiny installed. If shiny is installed on the target, it may be the incorrect version.

Workaround is to use a `library(shiny)` statement.

**Comment by aronatkins** [comment]
The `manifest.json` contains a shiny dependency while the `packrat.lock` does not.

**Comment by jmcphers** [comment]
I think we should fix this on the packrat side--if you're bundling a Shiny project with Packrat it should bundle Shiny for you. @kevinushey, do you agree?

**Comment by kevinushey** [comment]
Sounds good to me. I feel like initially, we needed to include `library(shiny)` at the top of the `ui.R` / `server.R` scripts, but it seems like this is no longer the case.

Should we add some heuristics to packrat that attempts to detect if this is a Shiny application, then? I guess we would look for:

1. ui.R with a `shinyUI()` call + server.R with `shinyServer()` call,
2. `app.R` with appropriate call (need to consult documentation to remember what that is),
3. `DESCRIPTION` file with `Type: Shiny`.

Does that sound correct? Would there be any users who would initialize a shiny application not using those two main entry points (aside from `app.R` users)?

**Comment by jmcphers** [comment]
That sounds good, and the `app.r` call is to `shinyApp()`. 

We also need to include Shiny when the directory contains an R Markdown document that has `runtime: shiny` in its YAML preamble. See here for an example of how to detect this:

https://github.com/rstudio/rsconnect/blob/master/R/bundle.R#L72

**Comment by aronatkins** [comment]
The `server.R` is no longer required to call `shinyServer`:
https://github.com/rstudio/shiny/blob/d39c93ee7eb01b8688d8a54ca1f33b4344732236/R/server.R#L201

It also appears that `ui.R` does not need to call `shinyUI`:
https://github.com/rstudio/shiny/blob/d39c93ee7eb01b8688d8a54ca1f33b4344732236/R/shinyui.R#L80

**Comment by aronatkins** [comment]
Here is how shiny looks for an app dir:
https://github.com/rstudio/shiny/blob/d39c93ee7eb01b8688d8a54ca1f33b4344732236/R/app.R#L93

**Comment by aronatkins** [comment]
Also note that `ui.R` is optional. https://github.com/rstudio/shiny/blob/d39c93ee7eb01b8688d8a54ca1f33b4344732236/R/app.R#L122

**Comment by kevinushey** [comment]
The amount of complexity here makes me think it would be better for packrat to provide a way for people to easily declare dependencies explicitly (in a way that feels less cludgey than throwing `library(shiny)` in a file somewhere).

It doesn't feel very maintainable for packrat to attempt to track (in a way independent of the `shiny` package itself) what a `shiny` application might look like; instead it should be easy for the author to declare the dependency explicitly (maybe as a project option, or otherwise).

Any thoughts? Or should we go the 'infer whether this is a `shiny` application from the contents` route? In the end, `rsconnect` is going to call some packrat API to infer dependencies, so since we have control of both ends it's probably easiest to just go the 'declare explicit dependencies' route.

**Comment by aronatkins** [comment]
rsconnect is already attempting to determine what sort of deploy it is performing and can make some deployment assumptions about what dependencies must be ensured.

Thinking more generally about packrat, it makes sense for a user to inject dependencies into a packrat bundle in order to make it more portable.

rsconnect is already computing dependencies for its `manifest.json` 
https://github.com/rstudio/rsconnect/blob/master/R/dependencies.R#L55
and forces `shiny` into all dependency sets (perhaps wrongly).

It feels like there are two dependencies that need to be injected into the `packrat.lock`:
* `shiny` for shiny apps
* `rmarkdown` for rmarkdown files
These dependencies are best discovered by rsconnect. All other dependencies should be discovered by analyzing the bundled files (and transitive dependencies of the injected requirements).

**Comment by jjallaire** [comment]
In the case of reconnect using pack rat under the hood, the user has no
idea they are using pack rat so wouldn't be able to provide a 'shiny'
annotation.

For shinyapps we implicitly include shiny (precisely because library(shiny)
isn't required. I don't see how we get around doing something similar for
rsconnect (especially when executing within 'deployApp')

On Mar 4, 2015, at 7:07 PM, Kevin Ushey <notifications@github.com> wrote:

The amount of complexity here makes me think it would be better for packrat
to provide a way for people to easily declare dependencies explicitly (in a
way that feels less cludgey than throwing library(shiny) in a file
somewhere).

It doesn't feel very maintainable for packrat to attempt to track (in a way
independent of the shiny package itself) what a shiny application might
look like; instead it should be easy for the author to declare the
dependency explicitly (maybe as a project option, or otherwise).

Any thoughts? Or should we go the 'infer whether this is a shiny
application from the contentsroute? In the end,rsconnect` is going to call
some packrat API to infer dependencies, so since we have control of both
ends it's probably easiest to just go the 'declare explicit dependencies'
route.

—
Reply to this email directly or view it on GitHub
<https://github.com/rstudio/rsconnect/issues/21#issuecomment-77278985>.

**Comment by jmcphers** [comment]
It'd be very straightforward to have the rsconnect package trick Packrat into including the right stuff in the lockfile, by e.g. writing a temporary .R file into the temporary directory from which the bundle is built prior to snapshotting and removing it before we actually tar up the contents. 

That's the most straightforward fix, and I'm tempted to make it so we can get over this roadblock while we work out the details of some of the other approaches discussed here.

Longer-term, my view is that Packrat itself should be inferring dependencies from contents, so that e.g. if you `packrat::bundle()` a directory containing a Shiny app, you get Shiny included as a dependency. I agree with @kevinushey that it feels wrong to couple Packrat and Shiny in this way (for instance, to embed knowledge in Packrat about what constitutes a Shiny application layout on disk), but the alternative is that we have to teach people how to inject the dependency explicitly if they're outside our toolchain and overall I think that's a bigger cost.

Packrat already has this kind of specialized knowledge about other packages; for instance, if you have an R Markdown document, it knows to include the rmarkdown package, and to scrape the YAML header for additional dependencies, which are also package-specific (see: https://github.com/rstudio/packrat/blob/e1b7e98312828129e54e8cd0e018f6d99ecef20c/R/dependencies.R#L116). I don't think this is much different.

**Comment by kevinushey** [comment]
Good point re: R Markdown documents. Okay, I'll add similar inference re: "is this a Shiny application?" to Packrat.

**Comment by aronatkins** [comment]
Thanks, @jmcphers. Should make it easier for folks starting with one of the existing examples which lack `library(shiny)`.
