### ISSUE TITLE
Unable to deploy shiny depending on packages from CRAN, bioconductor and Github

### ISSUE THREAD

**Issue by JiajinChen** [rstudio/rsconnect#274]
I wrote a shiny app,it depend on some packages from CRAN,bioconductor and Github. I want to deploy it on shinyapps.io,but get some error. Firstly, I use the guide on shinyapp.io user guide. Just using R package "rsconnect",and set account using setAccountInfo and then use rsconnect::deployApp to deploy my app, but get the following error. 
![1](https://user-images.githubusercontent.com/34928643/40307599-c3e6dd32-5d35-11e8-9206-2f43b0b09401.png)
And then I add options(repos = BiocInstaller::biocinstallRepos()) It allowed me to install packages on bioconductor,but my app also depend on packages from Github, so get the following Error.
![2](https://user-images.githubusercontent.com/34928643/40307605-cdd08d52-5d35-11e8-86c4-ea52a6972778.png)

**Comment by JiajinChen** [comment]
PS. SVGAnnotation is a package from Github.

**Comment by lcolladotor** [comment]
@tamburinif's solution at https://github.com/rstudio/rsconnect/issues/384#issuecomment-551305199 worked for my case. It's similar to code you ran though but with `options(repos = BiocManager::repositories())`. In my case, I got an error that said: 

```
## lots of stuff then:
Preparing to unpack .../libumfpack5.7.1_1%3a4.4.6-1_amd64.deb ...
Unpacking libumfpack5.7.1:amd64 (1:4.4.6-1) ...
Selecting previously unselected package libspqr2.0.2:amd64.
Preparing to unpack################################# End Task Log #################################
Error: Unhandled Exception: Child Task 666354178 failed: Error building image: Error fetching Rsamtools (2.2.0) source. Error downloading package source. Please update your BioConductor packages to the latest version and try again: <BioconductorPackageSource rep
```

which was because I had `Rsamtools` version 2.2.0 instead of the latest 2.2.1 (BioC 3.10 release; current one) installed in my computer. So running `BiocManager::install()` and making sure I had all the latest packages helped me.

As for GitHub packages, at https://community.rstudio.com/t/deploy-failed-when-add-github-package-into-shiny/18289/4 they emphasize that you should have installed the GitHub dependencies with `install_github()` (from `remotes` package, formerly inside `devtools`) so maybe double check that.

**Comment by jmcphers** [comment]
Correct; you need to use `install_github` so that the Github remote information metadata is written (otherwise there is no way to tell where the package came from!).
