### ISSUE TITLE
Error: Unable to retrieve package records for the following packages: - "RColorBrew"

### ISSUE THREAD

**Issue by lotwij** [rstudio/rsconnect#294]
Hi,

I got an error when I try to publish a shiny app. I got the following error:
```
Error: Unable to retrieve package records for the following packages:
- "RColorBrew"
In addition: Warning message:
In FUN(X[[i]], ...) :
  Package 'RColorBrew' not available in repository or locally
Execution halted
```

when I try to install the package it says:
```
> install.packages("RColorBrew")
Installing package into ‘C:/RLIBS’
(as ‘lib’ is unspecified)
Warning in install.packages :
  package ‘RColorBrew’ is not available (for R version 3.4.4)
```
I tried installing the RColorBrewer package, it doesn't solve the problem. I also tried to leave all the color commands out of the script, but it still gives the same error... Could anyone help me? Would really appreciate it :)

**Comment by jmcphers** [comment]
We can't generally help with questions here (this issue tracker is for bugs with the package itself). Try asking your question here:

https://community.rstudio.com/c/shiny

That said, since your app is ostensibly working fine without RColorBrew, I'd recommend simply removing whatever code references that package so that the deployment mechanism doesn't try to add it as a dependency.
