### ISSUE TITLE
include the ability to specify the email recipient

### ISSUE THREAD

**Issue by macek2** [rstudio/rsconnect#337]
For example, I may want to send an email to person A if one condition is true, but send the email to person B if the condition is false. I don't believe that there is a `rsc_email_recipient` option, but it would be amazing to have

**Comment by slopp** [comment]
@macek2  Thank you for opening this request! I've moved it to our internal backlog for RStudio Connect (since the feature isn't directly related to the rsconnect package).

We're very interested to hear more about your experience generating emails - what has gone well, what else could go better? Can you shoot me an email at sean@rstudio.com if you're interested in setting up a time to chat.

**Comment by macek2** [comment]
Will do!
