### ISSUE TITLE
Problems with deployments depending on the BH package

### ISSUE THREAD

**Issue by johanneswaage** [rstudio/rsconnect#361]
When deploying to Connect with writemanifest for projects depending on the BH library, rsconnect errors, as BH contains more than 10,000 files. Many tidyverse packages depends directly or indirectly on BH, so perhaps a more sensible default is needed.
Thanks

**Comment by jmcphers** [comment]
It's somewhat surprising that BH is being bundled with your project! There shouldn't be a need for it to be included, and anecdotally most people have no trouble deploying Tidyverse code to Connect.  Can you describe your usage of BH in more detail? Where do you install it from?

**Comment by johanneswaage** [comment]
Installing latest version of dplyr (0.8.3) with renv (0.8.2) enabled puts BH in the local library as well as the renv lockfile.

**Comment by kevinushey** [comment]
dplyr links to the BH package, so it is indeed required in general by projects using the tidyverse.

It sounds like the issue here is instead that the dependency discovery machinery is picking up files / folders within the `renv/library` folder, when it shouldn't?

It would be helpful if you could provide the exact error you're seeing (with a screenshot if appropriate).

**Comment by aronatkins** [comment]
`rsconnect` does not include `renv` when analyzing bundles as of https://github.com/rstudio/rsconnect/pull/367. This issue was created before that change. We believe that calls to `writeManifest` should no longer have the problem described here.

When handling deployments itself (not the `writeManifest` approach) `rsconnect` does not include the `renv` activation code as of https://github.com/rstudio/rsconnect/pull/462.

There is one remaining wrinkle -- when deploying to RStudio Connect from git or using the deployment APIs, the `renv` activation code is usually still within the `.Rprofile` file. This is a known issue that needs addressing.
