### ISSUE TITLE
Publishing Accounts Not Visible After Updating R

### ISSUE THREAD

**Issue by trestletech** [rstudio/rsconnect#39]
Since RStudio uses versioned user libraries, the rsconnect package "won't be installed" after an update to the version of R. This is reasonable behavior, but one undesirable effect is that when viewing the Settings > Publishing window, it appears that a user has no publishing accounts until after they go to install something -- at which point they're prompted to install rsconnect. 

Might be nice to bundle the account listing code in the IDE so we're not dependent upon having rsconnect available in our current library?

**Comment by aronatkins** [comment]
We include both rsconnect and rmarkdown in recent daily builds. I'm pretty sure that new rsconnect builds are installed behind the scenes for certain actions. Maybe the Settings>Publishing view is different. @jmcphers?

**Comment by trestletech** [comment]
Yeah, we usually prompt for install when you do something like click a publish button. But we don't do that when you're just viewing your settings.

**Comment by aronatkins** [comment]
And once you have rsconnect installed, subsequently there are silent upgrades. (according to @jjallaire). The settings dialog is different.

**Comment by jmcphers** [comment]
This was the original implementation for the Publish section of the settings dialog--if you didn't have rsconnect installed it would hide the entire account list and prompt you to install it (non-modally), instead of showing that you didn't have any accounts. I think we turned this off because it felt a little naggy and you do get prompted to install the package whenever you attempt to take any action, such as adding an account or publishing content.

Silent upgrades only apply if
a) the package is already installed in the current library, and
b) the existing installation was performed by RStudio (vs. installed by devtools, etc.) and
c) the user would otherwise be prompted (i.e. silent upgrades aren't ever performed proactively) 

So they're really irrelevant here since (a) isn't satisfied, and the settings dialog doesn't do (c). 

I'm pretty hesitant to bundle the account listing code in the IDE. Right now the rsconnect package owns the storage format for account metadata and we're free to modify the format as needs change as long as the rsconnect package can transition older formats to newer ones (we did this e.g. when removing the shinyapps package). Bundling the code in the IDE means we have to support the existing format for quite a while since older versions of the IDE are going to need to be able to read it.

I think we either live with the current behavior (which IMO is not terrible--it's recoverable and not going to be a frequent annoyance) or we add some light treatment to the publish settings view that hints that you need to install rsconnect if it isn't installed.

**Comment by trestletech** [comment]
Sure -- those all seem like reasonable behaviors. Maybe the compromise there is just to have some text in the accounts dialog that tells you why it's empty if you don't have rsconnect installed. That would be perfectly appropriate in my mind.

Of course, not urgent. Just a note.

**Comment by jmcphers** [comment]
Just chatted w/ @jjallaire about this. We think the best solution is to add some UI to the publish settings view when the following are both true:

a) you don't have the RSConnect package installed
b) your rsconnect account settings folder is non-empty

This way the experience doesn't change for new users, but users who upgrade R after connecting accounts will see a helpful hint. It does mean hard-coding the path to the rsconnect account storage folder in the IDE but I think that's a lot less likely to change than the organization and contents thereof. 

I'm closing this issue on RSConnect and I'll knock out the IDE change today or tomorrow (it's not terribly expensive).

**Comment by trestletech** [comment]
Perfect. Thanks, guys.
