### ISSUE TITLE
writeManifest() is unable to determine the repository for internal RSPM package

### ISSUE THREAD

**Issue by stufield** [rstudio/rsconnect#419]
I have a series of internal packages hosted in a local RStudio Package Manager repository (which also includes a pass thru to all of CRAN), and I call it `internal-plus-cran` in the RSPM repo. In attempting to write the `manifest.json` file via `rsconnect::writeManifest()`, it appears unable to locate the internal packages and I receive the following warnings/error:

```
Warning: Unable to determine the repository for package pkgA
Warning: Unable to determine the repository for package pkgB
Warning: Unable to determine the repository for package glmnet
Error: 
* Unable to determine the location for some packages. Packages must come from a package
   repository like CRAN or a source control system. Check that options('repos') refers to a
   package repository containing the needed package versions.
```

Here, `pkgA` and `pkgB` are internal packages located inside RSPM. I cannot explain the `glmnet` warning but in the past this has not resulted in API failure. 

Interestingly, I do NOT get this warning when publishing the API the "traditional" way via the RStudio GUI "publish" button. My assumption is that the same (or similar) function was being called "under the hood" but there seems to be a difference here.

Additionally I set:
```
options(repos = c(internal_plus_cran = "https://rstudiopm.mycompany.com/internal-plus-cran/"))
```

The curious part, is the the "CRAN packages" within my RSPM repository *ARE* found! It's only the internal packages that are not. This seems to be the key feature to a solution, I just haven't been able to debug it yet.

Any help would be greatly appreciated,
Thanks,
Stu

**Comment by slopp** [comment]
Hi Stu! Sorry for the trouble here. Would you mind sending an email to support@rstudio.com so we can be sure to follow up quickly?

I have a few hunches for what might be going on, but that support thread will be the best channel to investigate. 

A few questions that could help:
1. I assume you're on the latest versions of rsconnect and packrat... but could you confirm?
2. Are pkgA and pkgB local packages you've added to RSPM? Or are they Git-pulled packages?

It would also be really helpful if you could send us the manifest, and versions of RSPM and RSC.

Hope you are doing well in this crazy time, we'll get this sorted it out because it should 100% work!

**Comment by stufield** [comment]
Hi Sean!

Sure thing I'll send over an email to RS support. To get to your direct questions:

- using the dev version of `rsconnect v0.8.16.9001` and `packrat v0.5.0`
- Yes,  pkgA and pkgB local packages (company internal) added to RSPM. Not pulled from a public Git repository, but from a local BitBucket repo.
- RSPM and RSC were both updated recently (this week in fact)

Thanks Sean for your quick response, yes, crazy times.

**Comment by jmcphers** [comment]
Closing since we'll handle this over support. Thanks for the feedback @stufield!

**Comment by laurejo1** [comment]
I have the same issue.
