### ISSUE TITLE
Check packrat dependencies before uploading

### ISSUE THREAD

**Issue by maximilianmordig** [rstudio/rsconnect#421]
The packrat lockfile is created with `packrat::.snapshotImpl` and warnings about packages that could not be snapshotted, e.g. because installed from source, appear as warnings, but only at the end once the bundle was uploaded and consequently failed after quite some time of waiting.

To avoid this, I do the following:
```
options("rsconnect.pre.deploy" = function(appPath) {
  # fails if packages are not snapshottable
  packrat::snapshot(appPath, dry.run = TRUE)
})
```
Is it possible to add this check by default, i.e. put it right before the execution of the `preDeploy` function? I.e. here:
https://github.com/rstudio/rsconnect/blob/40c162bf3c4cd9b10deed82e1df9ec1b0c107c1f/R/deployApp.R#L221

Another inconvenience with the current workaround is that this option is not picked up, even when put into the .Rprofile, when the app is deployed by clicking `RunApp -> Publish app` in the RStudio UI.

needed @Roche

**Comment by jmcphers** [comment]
> Another inconvenience with the current workaround is that this option is not picked up, even when put into the .Rprofile

The IDE doesn't run `.Rprofile` for the deployment session since it needs a clean session. You can, however, put it into `.rsconnect_profile` instead; see `?rsconnectOptions` for details.

Snapshotting is time-consuming and not a problem for most users so running it twice (a dry run prior to publish and then a real invocation during deploy) is not something we are likely to do by default. We recommend using the above pre-deploy hook with `.rsconnect_profile` to set this up.
