### ISSUE TITLE
Renaming shinyapps.io accounts breaks rsconnect (sometimes)

### ISSUE THREAD

**Issue by kippandrew** [rstudio/rsconnect#49]
You can rename your account in shinyapps.io, this can break rsconnect since the account name is written locally.

**Comment by hadley** [comment]
Are you thinking of what happens if the user does this?

```R
removeAccount("old-name", "shinyapps.io")
setAccountInfo("new-name", "shinyapps.io", ...)
```

That no longer errors, because `deployments()` gained a `excludeOrphaned = TRUE` default, so deployments to servers that no longer exists aren't reported. That means you'll get a prompt like this:

```R
Found multiple accounts.
Which one do you want to use?
1: hadley@colorado.posit.co
2: hadley@connect.rstudioservices.com
3: hadley@posit.cloud
4: hadley-testing2@shinyapps.io
5: hadley@shinyapps.io
Selection: 4
Discovered a previously deployed app named "shinyapp-appr"
(View it at <https://hadley-testing2.shinyapps.io/shinyapp-appr/>)
What do you want to do?
1: Update the existing app.
2: Create a new app with automatically generated name ("shinyapp-appr-1").
3: Abort this deployment and supply a custom `appName`.
```

Unless there's something else you're thinking of, I think that this issue is now closed.
