### ISSUE TITLE
rsconnect/packrat writeManifest - mechanism to exclude R specific packages

### ISSUE THREAD

**Issue by slodge** [rstudio/rsconnect#505]
We've recently seen some issues where rsconnect `writeManifest` has somehow pulled in the `credentials` package into the `manifest.json` file.

This is possibly via a path of `devtools` to `gert` to `credentials` somehow being included (I'm still looking to try to work out what is happening).

The result of this is that deployments to RStudio Connect fail - as the credentials package tries to access git config information which is beyond its security permissions (which is good).

I'd like to try to find some way to exclude this R package. 

I don't mind if this is in the writeManifest step or on the server in the deployment step - e.g. I discovered recently with the Python there's a way (on the server at least) to ignore packages (https://docs.rstudio.com/connect/admin/appendix/configuration/#Python.ProhibitedPackage). 

I appreciate this is a bit vague as a feature request/question - hope it's ok to log this as an issue.

**Comment by kevinushey** [comment]
Since Packrat is used to generate the lockfile, you should be able to ignore it by setting the Packrat option explicitly; e.g.

```
ignored <- packrat::opts$ignored.packages()
packrat::opts$ignored.packages(c(ignored, "credentials"), persist = FALSE)
```

This could be set in the `.rsconnect_profile` as described in `?rsconnect::rsconnectOptions`.

(note: haven't actually tested this approach but I believe it would work?)

**Comment by slodge** [comment]
Thanks

Have also had superb response back from the credentials maintainers team...

But will look at how to use this too

**Comment by jmcphers** [comment]
Closing this since I think @kevinushey's workaround should do the trick for now (but let us know if it doesn't!)

**Comment by pat-s** [comment]
Hi everyone,

I've tried this and inspected what `rsconnect::writeManifest()` does bit more in detail as it did not work OOB.

Turns out that within `rsconnect::writeManifest()` `packrat::.snapshotImpl()` is called which honors the ignored pkgs when setting the option as described above.

To verify this I called

```r
packrat::.snapshotImpl(project = ".",
                       snapshot.sources = FALSE,
                       fallback.ok = TRUE,
                       verbose = TRUE,
                       implicit.packrat.dependency = FALSE,
                       infer.dependencies = TRUE)
```

with the package ignored and without and the resulting `packrat.lock` file reflected the change.

However, after this call in `rsconnect::writeManifest()` something else seems to happen which pulls in the ignored package again and it appears in the final `manifest.json`.

I tested this in a simple demo project which had a `library(<package>)` call in an Rmd file which only consisted of this one code chunk.
