### ISSUE TITLE
Api key based connection doesn't work

### ISSUE THREAD

**Issue by officialpatterson** [rstudio/rsconnect#507]
Hi All,

Working on doing some programmatic deployments using the rsconnect package and the `connectApiUser()` function. Connecting the user is fine and completes successfully, but if I try to use it in any way it doesn't work and I get the below error:
```
> rsconnect::applications(account = "singlehostaccount")
Error in response[[listName]] : subscript out of bounds
```
The error isn't very informative to say the least!

**Comment by colearendt** [comment]
Worth noting that another approach may be to use the [`connectapi`](https://github.com/rstudio/connectapi). It aims mostly at implementing a client for the public [RStudio Connect Server API](https://docs.rstudio.com/connect/api/) and can be useful for programmatic workflows

**Comment by officialpatterson** [comment]
Much appreciated as that’s exactly what I’m looking for. Frustratingly rstudio doesn’t list it as a client library on their API page and it isn’t high on Google’s search results either :/

**Comment by colearendt** [comment]
Although I can't help directly with the Google results (but you can, by using it!! 😄 ), I will see if there is a nice way to surface it better in the docs. We are shooting for a CRAN release soon, so that will hopefully help. Please let us know if you run into any issues, or feel free to peruse / share on [RStudio Community](https://community.rstudio.com/c/r-admin/rstudio-connect/27) 😄
