### ISSUE TITLE
Better Linting / Error for caret / parsnip implied dependencies

### ISSUE THREAD

**Issue by slopp** [rstudio/rsconnect#519]
Tickets like this are becoming more common: https://rstudioide.zendesk.com/agent/tickets/62463

Analysis that use caret or parsnip will fail to deploy to RSC unless the user adds an explicit library call to load the modeling engine.

Slack thread: https://rstudio.slack.com/archives/CFLAY27EH/p1621284777030900

**Comment by slopp** [comment]
Related: https://github.com/rstudio/renv/issues/749

**Comment by hadley** [comment]
Since I don't see any way to tackle this automatically (i.e. determining which of the suggested dependencies is installed is really hard), we might want to recommend an approach like [capsule](https://github.com/milesmcbain/capsule), where you run the script locally using the same package environment you'll get when deploying.

**Comment by hadley** [comment]
Now tracking general issue in #725
