### ISSUE TITLE
Failed to install package sources missing

### ISSUE THREAD

**Issue by officialpatterson** [rstudio/rsconnect#527]
Hi,

Running into a deployment issue where I get the below error message:
`
[Connect] 2021/07/13 09:00:57.701652288 Error in installPkg(pkgRecord, project, repos, lib): Failed to install myPackage(1.6.0.116410): sources missing at /opt/rstudio-connect/mnt/app/packrat/src/myPackage/myPackage_1.6.0.116410.tar.gz
`

**Comment by aronatkins** [comment]
It appears as if `myPackage` is not available for installation on the RStudio Connect server. This is usually because the package is not hosted by a CRAN-like repository or in a public source control system. The `rsconnect` package can fail to determine how to obtain a package if it was manually installed from source, for example.

If possible, could you install this package from a package repository or from source control (e.g. git) and try re-deploying?

If you continue to have trouble with your deploy, please reach out to RStudio support <support@rstudio.com>.
