### ISSUE TITLE
We do not need to specify contentCategory in deployApp

### ISSUE THREAD

**Issue by omar-rs** [rstudio/rsconnect#623]
This was removed with https://github.com/rstudio/rsconnect/pull/304.  

Unfortunately, it returned with the fix to https://github.com/rstudio/rsconnect/issues/204 (https://github.com/rstudio/rsconnect/commit/9e768e87c9a63885f175ccbc4ed69eb6c503f0f2; no PR?)

This check is happening ahead of the call to bundleApp, which means that we have not yet determined the appMode.  This issue was raised as part of https://github.com/rstudio/rsconnect/pull/621 but was deemed to be too large of a refactor, thus creating this separate issue.

**Comment by hadley** [comment]
Can you give me a bit more context? It doesn't seem like you do currently need to specify `contentCategory`.

**Comment by aronatkins** [comment]
The `deployAPI` call should not be providing `deployApp(..., contentCategory = "api")`. It was removed, but then accidentally re-added with some other work.

Connect has some compatibility code to disregard incoming `contentCategory = "api"`, but it would be better for `rsconnect` to stop setting the field.

Unfortunately, the shinyapps.io "unsupported" check uses `contentCategory` (in order to err client-side). It should rely on `appMode`, but that information is not available yet. The "err if attempting to deploy an API to shinyapps.io" check should somehow shift after we compute the content metadata (files, appmode, etc).

**Comment by hadley** [comment]
Doesn't #619 imply we can now remove that check? Or did I misundertand that issue.

**Comment by aronatkins** [comment]
You're right (#619). I had thought that we would continue to catch this on the client, but it seems like folks are OK with server-side enforcement.
