### ISSUE TITLE
`deploymentTarget()` doesn't use `appId`

### ISSUE THREAD

**Issue by hadley** [rstudio/rsconnect#701]
Shouldn't it?

**Comment by hadley** [comment]
Think about this: If the parameters supplied don't match any deployments, but other deployments exist, should we warn the user?

**Comment by hadley** [comment]
@aronatkins do you have any sense of how `appId` is supposed to be used in `deployApp()`? There are many scenarios I can imagine, but none of them seem particularly compelling compared to supplying `appName`.

**Comment by aronatkins** [comment]
The `rsconnect-python` examples show how to use the CLI (a Python application) to target content created by someone else. This example probably should be in terms of the content GUID rather than the numeric identifier, but does show the workflow.

https://docs.posit.co/connect/user/publishing-cli/#updating-a-different-deployment

I couldn't find an example using this R package, but the same idea applies.

The `appId` is not directly used by `deploymentTarget` other than recording the value on the returned object. `applicationForTarget` then uses the `appId` to fetch that specific content.

The `appName` is insufficient when collaborating because _your_ content named "shiny" is not _my_ content named "shiny". The name-based search will find _owned_ items with that name; it restricts its search to content owned by the requesting user (see the `account_id` filter in `listApplicaitons`).

**Comment by hadley** [comment]
What if we just error if `appId` is supplied and we find an existing deployment? Then we can reserve specifying `appId` only for the case where you're attempting to update an add deployed by someone else, where the original deployment record has been lost.

**Comment by aronatkins** [comment]
The `appId` feels like it should take higher priority than the name/title.

1. I deploy something. I lose the `rsconnect` directory but want to continue to deploy to that location. I use `appId`. Empty `rsconnect` directory.
2. I deploy something. I give you permission to deploy to that location. You use `appId`, which is not related to the contents of your `rsconnect` directory.
3. You and I can both deploy to some location; we use a shared script, containing `appId` to run that deploy. The contents of the `rsconnect` directory may or may not overlap with `appId`.

Specifying `appName` feels like "search for this thing", while specifying `appId` feels like "use this exact thing".

**Comment by hadley** [comment]
Hmmm, interesting. I was thinking that you'd supply `appId` once, in order to set up the deployment record, then never again, relying on the information stored on disk.

In your scenario, what happens if you supply `appName` and `appId` and they don't match?

**Comment by aronatkins** [comment]
* Multiple accounts: err, as the target location is ambiguous.
* Mismatch: `appId` wins, but probably warn about the inconsistency. The server `content.name` can change and is not guaranteed to stay in sync with the client-recorded name. (we may have metadata-updates somewhere?)
