### ISSUE TITLE
Republishing to posit.cloud fails after updating rsconnect

### ISSUE THREAD

**Issue by ronblum** [rstudio/rsconnect#871]
1. Install `rsconnect` 0.8.29.
2. <kbd>File -> New Project -> New Directory -> Shiny Application</kbd>
3. Provide directory name and click <kbd>Create Project</kbd>.
4. Publish to posit.cloud.
5. Update `rsconnect` to dev version.
6. Republish.

Republishing fails in the UI, with the message "No output found for id=" etc.

<img width="280" alt="no_output_found" src="https://github.com/rstudio/rsconnect/assets/31009952/a112f310-63b7-472e-8f24-4b3873bfbad0">

1. Fails for R Markdown as well, not just Shiny app.
2. Works with rsc.radixu.com.
3. Republishing with the same version of `rsconnect` works.
4. Tested with
    - Posit Workbench 2023.06.0+421.pro1 and R 3.6.3 on Ubuntu 20.04.5 via Chrome on MacOS 13.4.
    - RStudio Desktop 2023.08.0-daily+46 and R 4.3.0 on MacOS 13.4.

**Comment by aronatkins** [comment]
@mslynch - This is likely related to the posit.cloud identifier changes -- could you investigate if this upgrade problem is genuine?

**Comment by mslynch** [comment]
This is genuine. The problem is that the IDE looks up applications using the appId, but we don't have the context to know whether it's the id of the content or the application. We may have to walk back on our DCF versioning approach and discover which it is through API calls. The alternative would be to make IDE changes to accommodate this, but I'd prefer not to go that way.

cc @omar-rs @hadley

**Comment by ronblum** [comment]
Verified with the development version (0.8.29.9000) of `rsconnect` using RStudio Server 2023.06.0+421.pro1 on Ubuntu 20.04.5 via Chrome on MacOS 13.4.
