### ISSUE TITLE
Port rsconnect to use httr

### ISSUE THREAD

**Issue by kippandrew** [rstudio/rsconnect#90]
`httr` is quickly becoming a standard package that people are using. Some users are confused because `rsconnect` does not use `httr`, or share its proxy config settings.

**Comment by scottmmjackson** [comment]
@hadley mentioned this. I agree.

**Comment by hadley** [comment]
Using the lower level curl package would also be fine, since that's what httr is built on top of. You should decide based on whether you want a high level or low level api

**Comment by jjallaire** [comment]
As a reminder for those not familiar with the package internals, we are already set up to use multiple http transports. Currently we have 3:

1) Use internal sockets
2) Use RCurl
3) Use system curl

Each of these is implemented in a single function here: https://github.com/rstudio/rsconnect/blob/master/R/http.R

So using httr would simply be a matter of adding a single function to this file, and then making it the new default (users that have problems with it can simply opt in to a different transport).

Anyway, just wanted to make the point that this is already well isolated, not a large or disruptive work item, and not really risky since it will sit well alongside what we already have.

**Comment by jmcphers** [comment]
We switched to `curl` instead.
