### ISSUE TITLE
Automating rsconnect::writeManifest()

### ISSUE THREAD

**Issue by joelgsponer** [rstudio/rsconnect#965]
Hi,
I use a couple of script to automate some of my app development workflows, one was to use the reconnect::writeManifest, git add,  commit and push in one script. This is useful to me as it takes some time and I can do something else while it is doing so.
But with the newer version this is not possible anymore as I have to specify what to do with the renv lock file:
![image](https://github.com/rstudio/rsconnect/assets/6795002/39af2893-8dfb-4a8b-b803-a8a8623446be)
Is there a way to circumvent this?  I could not find anything in the parameters that would fit the bill?
Thanks a lot

**Comment by aronatkins** [comment]
What versions of rsconnect and renv are you using?

The call to `rsconnect::writeManifest()` is probably prompting because some of the required packages are not installed.

Could you try updating to the latest CRAN releases of renv and rsconnect to see if they offer more information about what packages are missing?

If updating does not help, are you able to share your `renv.lock` or create a standalone project that exhibits the same behavior?

**Comment by joelgsponer** [comment]
Thanks for your answer.
Current renv version: 1.0.0
Current reconnect version:  1.0.1
---
Updated renv version: 1.0.2
Updated reconnect version:  1.0.2

-> This solved the problem.
Thanks

**Comment by joelgsponer** [comment]
Updating the libraries solved the problem
Thanks
