### ISSUE TITLE
CRAN labels for mac binaries are wrong (v1.1.0)

### ISSUE THREAD

**Issue by philhoward23** [rstudio/rsconnect#995]
https://cran.r-project.org/web/packages/rsconnect/index.html

Mac binaries have listed
macOS binaries:	r-release (arm64): [rsconnect_1.0.2.tgz](https://cran.r-project.org/bin/macosx/big-sur-arm64/contrib/4.3/rsconnect_1.0.2.tgz), r-oldrel (arm64): [rsconnect_1.0.2.tgz](https://cran.r-project.org/bin/macosx/big-sur-arm64/contrib/4.2/rsconnect_1.0.2.tgz), r-release (x86_64): [rsconnect_0.8.29.tgz](https://cran.r-project.org/bin/macosx/big-sur-x86_64/contrib/4.3/rsconnect_0.8.29.tgz), r-oldrel (x86_64): [rsconnect_1.1.0.tgz](https://cran.r-project.org/bin/macosx/contrib/4.2/rsconnect_1.1.0.tgz)
Old sources:	[rsconnect archive](https://cran.r-project.org/src/contrib/Archive/rsconnect)

I think that r-release should be swapped with r-oldrel for x86_64:
macOS binaries:	r-release (arm64): [rsconnect_1.0.2.tgz](https://cran.r-project.org/bin/macosx/big-sur-arm64/contrib/4.3/rsconnect_1.0.2.tgz), r-oldrel (arm64): [rsconnect_1.0.2.tgz](https://cran.r-project.org/bin/macosx/big-sur-arm64/contrib/4.2/rsconnect_1.0.2.tgz), r-oldrel (x86_64): [rsconnect_0.8.29.tgz](https://cran.r-project.org/bin/macosx/big-sur-x86_64/contrib/4.3/rsconnect_0.8.29.tgz), r-release (x86_64): [rsconnect_1.1.0.tgz](https://cran.r-project.org/bin/macosx/contrib/4.2/rsconnect_1.1.0.tgz)
Old sources:	[rsconnect archive](https://cran.r-project.org/src/contrib/Archive/rsconnect)

**Comment by philhoward23** [comment]
My issue was trying to update from rstudio and getting the old version

**Comment by aronatkins** [comment]
Restating:

The earlier test problems with 1.0.0, 1.0.1, and 1.0.2 prevented CRAN from publishing updated rsconnect binaries, which is why macOS Intel binaries are still stuck at 0.8.29. The test problems _should_ be avoided with 1.1.0, but we are still waiting for the CRAN build.

The underlying cause of the test failures was that the CRAN macOS Intel host has a _VERY_ old version of Pandoc. Some of the rsconnect tests were calling to rmarkdown, which requires a newer version of Pandoc. That incompatibility caused the test errors that blocked publishing.

The test failures should not occur with rsconnect 1.1.0, but we are still waiting for the CRAN build to be sure.

**Comment by philhoward23** [comment]
Thanks for the response! Install from source worked fine for me.

**Comment by aronatkins** [comment]
CRAN has 1.1.0 for all architectures.
